development:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: bowerrr_development
  pool: 5
  timeout: 5000
  username: bowerrr
  password:

test:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: bowerrr_test
  pool: 5
  timeout: 5000
  username: bowerrr
  password:

production:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: bowerrr_production
  pool: 5
  timeout: 5000
  username: bowerrr
  password:
